#!/usr/bin/env python
"""
To run the app from as an executable
Copy to your bin directory and set permissions
"""

from __future__ import absolute_import
import re
import sys

from aiida_post import app

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(app())
